algoritmo "semnome"
var
  i,f: inteiro
inicio
      Escreva ("Inicio: ")
      leia (i)
      escreva ("Fim: ")
      leia (f)
           se (I >= F) entao
              enquanto (I >= F) faca
              escreva (I, "...")
              I<- I-1
              fimEnquanto
           senao
              enquanto (I<= F) faca
              escreva (I, "...")
              I<- I+1
              fimEnquanto
           fimSe
fimalgoritmo
