algoritmo "semnome"
var
  N, s: Inteiro
  resp : caracter
inicio
      S <- 0
      resp <- "s"
      enquanto (resp = "S") faca
               Escreva ("Digite o valor ==> ")
               leia (n)
               S<- S + n
               Escreva ("Voce quer contunuar? [s/n] ")
               leia (resp)
      fimEnquanto
      Escreval (" A soma de todos os valores digitados e ", S)
fimalgoritmo
